; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

; ── Node PENGIRIM (TX) ──────────────────────────────────────
[env:lora_tx]
platform = espressif32
board = heltec_wifi_lora_32_V3
framework = arduino
monitor_speed = 115200
lib_deps =
    jgromes/RadioLib@^7.1.2
    adafruit/Adafruit MPU6050
    adafruit/Adafruit Unified Sensor
src_filter =
    +<main_node.cpp>
    +<comm.cpp>
    +<read_imu.cpp>
    +<read_soil.cpp>

; ── Node PENERIMA (RX) ──────────────────────────────────────
[env:lora_rx]
platform = espressif32
board = heltec_wifi_lora_32_V3
framework = arduino
lib_deps =
    jgromes/RadioLib @ ^7.1.2
src_filter = +<main_gateway.cpp>  ; hanya compile main1.cpp
